### PR TITLE
Several Changes made...

### PR DESCRIPTION
**Pull request by mamarilmanson**
My very first pull request... please forgive if it might cause some conflicts...

**Bugs/Todo:**
- Play _NoAmmoGunClicks.wav_ audio only once when ammo is empty _(currently being always played/looped upon left mouse button hold)_
- Delete NoAmmoGunClicks.mp3 _(not being used by Godot)_

**Changes:** 
- Changed resolution to small/godot default to fit my monitor _(temporary development adjustment)_
- Changed Player location upon spawn/game start
- Gravity -50 -> -60 _(might still need to rework to use actual gravity -9.8)_
- UI: HP and Bullets UI margin _(previously always on the very edge of the screen)_
- UI: Top progressbar margin
- Added green vfx when getting health pack, used animation player
- Changed to blurred red vfx border when taking damage, used animation player _(**PLEASE TAKE NOTE**: edited original blood.png file, please backup original in your main branch)_
- Reworked how damage and regen vfx were called using _AnimationPLayer_ node
- Currently commented out red/blood vfx flashing code from _HUD.gd_, might rewrite to work well with new _AnimationPlayer_ node blood vfx workflow

### CODE REVIEW

**Comment by liammuir** [comment]
I tried to run this, but it couldn't find any of the new nodes you created. I think you didn't add all of the files when making your commit. Could you please try adding all the files with _git add *_ and then committing again?

**Comment by liammuir** [comment]
About the gravity, I found that 9.8 wasn't enough to create a fun experience for the player. I ended up with -50 after some trial and error.

**Comment by mamarilmanson** [comment]
Added the updated file... Please check again...

**Comment by liammuir** [comment]
The UI changes are great! I think the health pack vfx make picking up a health pack feel more responsive. The margins helped greatly to improve readability when in full screen mode. The out of ammo sound is a nice touch even if it is bugged. 

I do have a few suggestions however. You put the animation code in the player script. while this works, it would have been better if you put it into the HUD script. Molecularity is a core concept of Godot. whenever possible, try to put code as low as possible on the tree of nodes. The vfx has a few flaws as well. The animation system bugs out when you get hit by multiple bullets or when you walk through multiple health packs. The system before used a number to control the blood opacity rather than an AnimationPlayer, and was able to handle these cases easily. 

I will merge the UI margin changes and the out of ammo sound effect into the main branch, but the vfx changes will not be incorporated into the project in their current state.

Thank you for submitting this pull request, and I hope your journey with Godot continues on!

**Comment by mamarilmanson** [comment]
Thanks... I'll try to take note of the health/damage vfx bugs and todo and fix them... hope to contribute more in the future...

**Pull request closed without merging**
